//go:build integration

// Integration tests run against a real PostgreSQL instance.
// They are excluded from normal "go test ./..." runs. Run them explicitly:
//
//	go test -tags=integration ./internal/api/ -v
//
// In CI, GitHub Actions provides a postgres service container and sets
// TEST_DATABASE_URL before this job runs.

package api_test

import (
	"bytes"
	"database/sql"
	"encoding/json"
	"fmt"
	"net/http"
	"net/http/httptest"
	"os"
	"testing"

	"github.com/gin-gonic/gin"
	_ "github.com/lib/pq"
	"golang.org/x/crypto/bcrypt"

	"db-design-project/internal/api"
	"db-design-project/internal/db"
)

// integrationRouter wires a real *sql.DB into the same gin engine main.go uses.
func integrationRouter(conn *sql.DB) http.Handler {
	gin.SetMode(gin.TestMode)
	r := gin.New()
	api.RegisterRoutes(r, db.New(conn))
	return r
}

// openTestDB opens the DB from TEST_DATABASE_URL, applies the schema, and
// registers cleanup.
func openTestDB(t *testing.T) *sql.DB {
	t.Helper()
	dsn := os.Getenv("TEST_DATABASE_URL")
	if dsn == "" {
		t.Fatal("TEST_DATABASE_URL must be set for integration tests")
	}
	conn, err := sql.Open("postgres", dsn)
	if err != nil {
		t.Fatalf("sql.Open: %v", err)
	}
	if err := conn.Ping(); err != nil {
		t.Fatalf("ping: %v", err)
	}
	applyIntegrationSchema(t, conn)
	t.Cleanup(func() { conn.Close() })
	return conn
}

// applyIntegrationSchema creates tables if they don't exist.
// password_hash is included here because it is missing from schema_postgres.sql.
func applyIntegrationSchema(t *testing.T, conn *sql.DB) {
	t.Helper()
	ddl := []string{
		`CREATE TABLE IF NOT EXISTS users (
			id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email         varchar(255) UNIQUE NOT NULL,
			full_name     varchar(255),
			password_hash varchar(255) NOT NULL DEFAULT '',
			created_at    timestamp DEFAULT now()
		)`,
		`CREATE TABLE IF NOT EXISTS products (
			id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			sku         varchar(64) UNIQUE NOT NULL,
			name        varchar(255) NOT NULL,
			description text,
			price       decimal(10,2) NOT NULL,
			available   bool DEFAULT true,
			created_at  timestamp DEFAULT now()
		)`,
		`CREATE TABLE IF NOT EXISTS orders (
			id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			user_id    int NOT NULL,
			status     varchar(50) DEFAULT 'pending',
			total      decimal(12,2),
			created_at timestamp DEFAULT now()
		)`,
		`CREATE TABLE IF NOT EXISTS order_items (
			id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			order_id   int NOT NULL,
			product_id int NOT NULL,
			quantity   int NOT NULL DEFAULT 1,
			unit_price decimal(10,2) NOT NULL
		)`,
	}
	for _, stmt := range ddl {
		if _, err := conn.Exec(stmt); err != nil {
			t.Fatalf("schema DDL failed: %v", err)
		}
	}
}

func truncateAll(t *testing.T, conn *sql.DB) {
	t.Helper()
	if _, err := conn.Exec(`TRUNCATE users, products, orders, order_items RESTART IDENTITY CASCADE`); err != nil {
		t.Fatalf("truncate: %v", err)
	}
}

func seedUser(t *testing.T, conn *sql.DB, email, password string) int32 {
	t.Helper()
	hash, err := bcrypt.GenerateFromPassword([]byte(password), bcrypt.MinCost)
	if err != nil {
		t.Fatal(err)
	}
	var id int32
	if err := conn.QueryRow(
		`INSERT INTO users (email, password_hash) VALUES ($1, $2) RETURNING id`,
		email, string(hash),
	).Scan(&id); err != nil {
		t.Fatalf("seedUser: %v", err)
	}
	return id
}

func seedProduct(t *testing.T, conn *sql.DB, sku, name, price string) int32 {
	t.Helper()
	var id int32
	if err := conn.QueryRow(
		`INSERT INTO products (sku, name, price, available) VALUES ($1, $2, $3, true) RETURNING id`,
		sku, name, price,
	).Scan(&id); err != nil {
		t.Fatalf("seedProduct: %v", err)
	}
	return id
}

func loginToken(t *testing.T, router http.Handler, email, password string) string {
	t.Helper()
	body, _ := json.Marshal(map[string]string{"email": email, "password": password})
	w := httptest.NewRecorder()
	r, _ := http.NewRequest(http.MethodPost, "/login", bytes.NewReader(body))
	r.Header.Set("Content-Type", "application/json")
	router.ServeHTTP(w, r)
	if w.Code != http.StatusOK {
		t.Fatalf("login: expected 200, got %d: %s", w.Code, w.Body.String())
	}
	var resp map[string]string
	json.NewDecoder(w.Body).Decode(&resp)
	return "Bearer " + resp["access_token"]
}

// ── Tests ──────────────────────────────────────────────────────────────────

func TestIntegration_LoginAndGetMe(t *testing.T) {
	conn := openTestDB(t)
	truncateAll(t, conn)
	seedUser(t, conn, "alice@example.com", "password123")

	router := integrationRouter(conn)
	token := loginToken(t, router, "alice@example.com", "password123")

	w := httptest.NewRecorder()
	r, _ := http.NewRequest(http.MethodGet, "/users/me", nil)
	r.Header.Set("Authorization", token)
	router.ServeHTTP(w, r)

	if w.Code != http.StatusOK {
		t.Fatalf("GET /users/me: expected 200, got %d: %s", w.Code, w.Body.String())
	}
}

func TestIntegration_LoginWrongPassword(t *testing.T) {
	conn := openTestDB(t)
	truncateAll(t, conn)
	seedUser(t, conn, "bob@example.com", "correctpass")

	router := integrationRouter(conn)
	body, _ := json.Marshal(map[string]string{"email": "bob@example.com", "password": "wrongpass"})
	w := httptest.NewRecorder()
	r, _ := http.NewRequest(http.MethodPost, "/login", bytes.NewReader(body))
	r.Header.Set("Content-Type", "application/json")
	router.ServeHTTP(w, r)

	if w.Code != http.StatusUnauthorized {
		t.Fatalf("expected 401, got %d", w.Code)
	}
}

func TestIntegration_ListProducts(t *testing.T) {
	conn := openTestDB(t)
	truncateAll(t, conn)
	seedProduct(t, conn, "SKU-001", "Widget", "9.99")
	seedProduct(t, conn, "SKU-002", "Gadget", "19.99")

	router := integrationRouter(conn)
	w := httptest.NewRecorder()
	r, _ := http.NewRequest(http.MethodGet, "/products", nil)
	router.ServeHTTP(w, r)

	if w.Code != http.StatusOK {
		t.Fatalf("expected 200, got %d", w.Code)
	}
	var products []map[string]interface{}
	json.NewDecoder(w.Body).Decode(&products)
	if len(products) != 2 {
		t.Fatalf("expected 2 products, got %d", len(products))
	}
}

func TestIntegration_GetProductByID_Found(t *testing.T) {
	conn := openTestDB(t)
	truncateAll(t, conn)
	id := seedProduct(t, conn, "SKU-003", "Thing", "4.99")

	router := integrationRouter(conn)
	w := httptest.NewRecorder()
	r, _ := http.NewRequest(http.MethodGet, fmt.Sprintf("/products/%d", id), nil)
	router.ServeHTTP(w, r)

	if w.Code != http.StatusOK {
		t.Fatalf("expected 200, got %d", w.Code)
	}
}

func TestIntegration_GetProductByID_Missing(t *testing.T) {
	conn := openTestDB(t)
	truncateAll(t, conn)

	router := integrationRouter(conn)
	w := httptest.NewRecorder()
	r, _ := http.NewRequest(http.MethodGet, "/products/99999", nil)
	router.ServeHTTP(w, r)

	if w.Code != http.StatusNotFound {
		t.Fatalf("expected 404, got %d", w.Code)
	}
}

func TestIntegration_CreateAndListOrders(t *testing.T) {
	conn := openTestDB(t)
	truncateAll(t, conn)
	seedUser(t, conn, "carol@example.com", "pass")

	router := integrationRouter(conn)
	token := loginToken(t, router, "carol@example.com", "pass")

	// Create
	body, _ := json.Marshal(map[string]float64{"total": 25.00})
	w := httptest.NewRecorder()
	r, _ := http.NewRequest(http.MethodPost, "/orders", bytes.NewReader(body))
	r.Header.Set("Content-Type", "application/json")
	r.Header.Set("Authorization", token)
	router.ServeHTTP(w, r)

	if w.Code != http.StatusCreated {
		t.Fatalf("POST /orders: expected 201, got %d: %s", w.Code, w.Body.String())
	}

	// List
	w = httptest.NewRecorder()
	r, _ = http.NewRequest(http.MethodGet, "/orders", nil)
	r.Header.Set("Authorization", token)
	router.ServeHTTP(w, r)

	if w.Code != http.StatusOK {
		t.Fatalf("GET /orders: expected 200, got %d", w.Code)
	}
	var orders []map[string]interface{}
	json.NewDecoder(w.Body).Decode(&orders)
	if len(orders) != 1 {
		t.Fatalf("expected 1 order, got %d", len(orders))
	}
}
