---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ecommerce-api.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: {{ include "ecommerce-api.fullname" . }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ecommerce-api.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: api-secrets
    creationPolicy: Owner
  data:
    - secretKey: database_url
      remoteRef:
        key: ecommerce/{{ .Values.secrets.env }}/rds
        property: connection_string
    - secretKey: jwt_secret
      remoteRef:
        key: ecommerce/{{ .Values.secrets.env }}/jwt
        property: jwt_secret
