apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
  - ../../base

# kustomize edit set image is run by CI before applying, replacing this tag with the git SHA
images:
  - name: 776235864987.dkr.ecr.us-east-1.amazonaws.com/ecommerce-api
    newTag: latest

patches:
  - path: patch-replicas.yaml
  - path: patch-secret-store.yaml
