apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../base

images:
  - name: 776235864987.dkr.ecr.us-east-1.amazonaws.com/ecommerce-api
    newTag: latest

patches:
  - path: patch-secret-store.yaml
