apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-secrets
spec:
  data:
    - secretKey: database_url
      remoteRef:
        key: ecommerce/staging/rds
        property: connection_string
    - secretKey: jwt_secret
      remoteRef:
        key: ecommerce/staging/jwt
        property: jwt_secret
